config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :offers do
    resources :reservations, only: [:new, :create]
  end
  post '/reservations/:id/deny', to: 'reservations#deny', as: 'reservation_deny'
  post '/reservations/:id/accepted', to: 'reservations#validate', as: 'reservation_validate'

  resources :reservations, only: [:index]
  #, only: [:destroy, :index]
  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end

end

app/views/reservations/partials/seniors/_offers.html.erb
<div class="tab-content d-none" id="senior-offers">
  <div class="tab-pane fade show active" id="nav-offers" role="tabpanel" aria-labelledby="nav-offers-tab mb-3">
    <% @my_offers.each do |offer| %>
      <%= link_to(offer_path(offer), class: 'text-decoration-none') do %>
        <div class="card-product my-3">
          <%= cl_image_tag(offer.photo.key) %>

          <div class="card-product-infos">
            <h2 class="text-dark"><%= offer.title %></h2>
            <p class="text-dark"><%= l(offer.date, format: :long) %></p>
            <div>  
              <%= link_to "Editer", edit_offer_path(offer), class:"btn btn-ghost"%> 
              <%= link_to "Supprimer", 
                          offer_path(offer),
                          method: :delete,
                          data: { confirm: "Etes-vous sûrs ?"},
                          class:"btn btn-ghost" %> 
            </div>
          </div>
        </div>
      <% end %>
    <% end  %>
  </div>
</div>