config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :offers do
    resources :reservations, only: [:new, :create]
  end
  post '/reservations/:id/deny', to: 'reservations#deny', as: 'reservation_deny'
  post '/reservations/:id/accepted', to: 'reservations#validate', as: 'reservation_validate'

  resources :reservations, only: [:index]
  #, only: [:destroy, :index]
  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
    Copyright © 2020-2021 Alex & Léo & Matt . All rights reserved.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon d-flex">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "convivapp.png" %>
  <% end %>
  <div class="right-elements">
    <div class="navbar-nav">
      <%# <a class="nav-link active" aria-current="page" href="#">Acceuil</a>  %>
<%# 
      <%= link_to "Accueil" , root_path, class: "nav-link active" %>
      <%# <%= link_to "Invitations", offers_path, class: "nav-link" %>
      <%# <%= link_to "Créer une invitation", new_offer_path, class: "nav-link" %>
      <%# <%= link_to "A propos", about_path, class: "nav-link" %> 
      

    </div>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      <%= link_to "Accueil" , root_path, class: "nav-link active" %>
      <%= link_to "Invitations", offers_path, class: "nav-link" %>
      <%= link_to "Créer une invitation", new_offer_path, class: "nav-link" %>
      <%= link_to "A propos", about_path, class: "nav-link" %>
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to current_user.first_name, reservations_path, class:"nav-link", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
              <%= cl_image_tag(current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false,
                :transformation=>[
                {:gravity=>"face", :height=>2000, :width=>2000, :crop=>"crop"},
                {:radius=>"max"},
                {:width=>200, :crop=>"scale"}
                ]) %>
            <% else %>
              <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%# <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <%= link_to "Mon compte", reservations_path, class: "dropdown-item" %>
              <% chatroom = Chatroom.find_by(name:"Bienvenue")%>
              <%= link_to "Mes messages", chatroom_path(chatroom.id), class: "dropdown-item" %>
              <%= link_to "Se deconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="button-login active">
            <%= link_to new_user_session_path, class: "nav-link btn btn-outline-warning py-2 px-4 custom-button-login-nav" do %>
              <span>Connexion</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>