config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :offers do
    resources :reservations, only: [:new, :create]
  end
  post '/reservations/:id/deny', to: 'reservations#deny', as: 'reservation_deny'
  post '/reservations/:id/accepted', to: 'reservations#validate', as: 'reservation_validate'

  resources :reservations, only: [:index]
  #, only: [:destroy, :index]
  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end

end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user, foreign_key: :user_id
  has_one :reservation, dependent: :destroy
  geocoded_by :address
  has_one_attached :photo
  after_validation :geocode, if: :will_save_change_to_address?
  acts_as_taggable
  acts_as_taggable_on :tags
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @offers = policy_scope(Offer)
    if params[:query].present?
      @offers = Offer.where("title ILIKE ?", "%#{params[:query]}%") + Offer.tagged_with(params[:query])
    else
      @markers = Offer.where.not(latitude: nil, longitude: nil).map do |offer|
        {
          lat: offer.latitude,
          lng: offer.longitude,
          info_window: render_to_string(partial: "info_window", locals: { offer: offer }),
          image_url:
            if offer.user.avatar.attached?
              if Rails.env.production?
                helpers.asset_url("https://res.cloudinary.com/convivapp/image/upload/v1636813977/production/#{offer.user.avatar.key}.jpg")
              else
                helpers.asset_url("https://res.cloudinary.com/convivapp/image/upload/v1636813977/development/#{offer.user.avatar.key}.jpg")
              end
            else
              helpers.asset_url("user.png")
            end
        }
      end
    end
  end

  def new
    @offer = Offer.new
    authorize @offer
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    @offer.tag_list = params[:offer][:tag_list]
    authorize @offer
    if @offer.save
      redirect_to offer_path(@offer), notice: "L'invitation a été créée avec succès !"
    else
      render :new
    end
  end

  def edit
  end

  def show
    @offer = Offer.find(params[:id])
    @user = current_user
  end

  def update
    if @offer.update(offer_params)
      redirect_to offer_path(@offer), notice: "L'invitation a été modifiée avec succès !"
    else
      render :edit
    end
  end

  def destroy
    @offer.destroy

    redirect_to offers_path
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
    authorize @offer
  end

  def offer_params
    params.require(:offer).permit(:title, :address, :date, :description, :photo, :name, :tag_list)
  end
end

app/views/offers/_info_window.html.erb
<%= link_to offer_path(offer) do %>
  <div class="card-category-mapboxxx" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path offer.photo.key, height: 300, crop: :fill %>')">
      <span id="title-title-mapbox"><%= offer.title %></span>
      <br>
      <span id="date-date-mapbox"><%= offer.date %></span>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Offers#edit</h1>
<%= simple_form_for @offer do |f| %>
  <%= f.input :title %>
  <%= f.input :address %>
  <%= f.input :date %>
  <%= f.input :description %>
  <%= f.input :meal %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/offers/index.html.erb
<div class="search-container"> 
  <div>
    <h1 class="title">Nous avons trouvé<span class="color"> <%= Offer.count %> invitations autour de chez vous ...</span></h1>
  </div>
  <div class= "search-form">
    <div class= "search-bar-custom">
      <%= form_tag offers_path, method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Recherchez un hobby ou un repas"
        %>
    </div>
    <div>
        <%= submit_tag "Rechercher", class: "btn search" %>
      <% end %>
    </div>
  </div>
</div>
<div class="main-container">

<% @offers.each do |offer| %>
  <%= link_to offer_path(offer) do %> 
    <div class="wrapper">
      <%= cl_image_tag(offer.photo.key.to_s, class:"plat top", width: 150, height: 150, gravity: :face) %>
      <h1 class="titre-de-offre"><%= offer.title %> </h1>
      <p class="description"><%= offer.description %></p>
        <% offer.tag_list.first&.split(" ")&.each do |tag| %>
          <div class="tags">
            <%= tag %>
          </div>
        <% end %>  
      <%# <p class="tags"> <%= offer.tag_list</p> %>
      <% if offer.user.avatar.attached? %>
        <%= cl_image_tag(offer.user.avatar.key, class:"plat", width: 150, height: 150, crop: :thumb, gravity: :face) %>
      <% else %>
        <%=  image_tag("user.png", class:"plat", width: 150, height: 150, crop: :thumb, gravity: :face) %> 
      <% end %>
  </div>
    <% end  %> 
<% end  %>
    <div id="map" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>" data-markers="<%= @markers.to_json %>"></div>
</div>

app/views/offers/new.html.erb
<div class="container-form">
  <h1 class="title-new-offer">Créer une invitation </h1>
  <%= simple_form_for @offer do |f| %>
    <%= f.input :title, label: "Quel est le titre de votre repas :"%>
    <%= f.input :address, label: "Quelle est l'adresse du repas :" %>
    <%= f.input :date, label: "Quelle est la date de votre repas:"%>
    <%= f.input :description, label: "Presentez vous:"%>
    <%= f.input :photo, as: :file, laber: "Une petite photo pour terminer ?" %>
    <%= f.input :tag_list, placeholder: "", label: "N'hésitez pas à nous partager vos activités préférées"%>
    <%= f.submit %>
  <% end %>
</div>

app/views/offers/show.html.erb
<div class="body ">
  <div class="container">
    <%= link_to "Retour aux propositions", offers_path(), class: "btn btn-show" %>
    <div class="row mb-2">
      <div class="cadre cadre-height">
        <div class="col-6 p-5 bg-white mb-2">
          <% if @offer.user.avatar.attached? %>
                <%= cl_image_tag(@offer.user.avatar.key, class:"avatar-card",
                  :transformation=>[
                  {:gravity=>"face", :height=>2000, :width=>2000, :crop=>"crop"},
                  {:radius=>"max"},
                  {:width=>200, :crop=>"scale"}
                  ]) %>
              <% else %>
                <%= image_tag "user.png", class:"avatar-card" %>
              <% end %>

          <span class="h2 d-block mt-3 font-weight-bold show-title-haut">
            Dejeuner avec <%= @offer.user.first_name %>
          </span>

          <p class="text-muted">
          <% if @offer.user.description.nil?%>
            Désolé ! Ce profil n'a pas de description d'enregistrer pour le moment. 😬
          <% else %>
            <%= @offer.user.description %>
          <% end %>
          </p>

          <div class="row text-left taglist-show-middle">
            <% @offer.tag_list.first&.split(" ")&.each do |tag| %>
              <div class="col-3 my-1">
                <span class="bg-blue px-4 d-inline-block">
                  <%= tag %>
                </span>
              </div>
            <% end %>
            <%# <% %w[Astronomie Lecture Astronomie Lecture Astronomie Lecture].each do |tag| %>
              <%# <div class="col-4 my-1">
                <span class="bg-blue px-4 py-2 d-inline-block">
                  <%= @offer.tag_list %>
                <%# </span>
              </div>
            <% end %>
          </div>

          <div class="row gx-4 bloc-star-and-meal">
            <div class="col-4 bg-blue-second ml-3 mt-3 py-2 px-3">
              <span class="h6 d-inline-block">
                Note
              </span>

              <div class="row">
                <span class="col-3 h3 d-block">
                  ⭐️
                </span>

                <span class="col h3 d-block">
                  4,8
                </span>
              </div>
            </div>

            <div class="col-4 bg-blue-second ml-3 mt-3 py-2 px-3">
              <span class="h6 d-inline-block">
                Nb de repas
              </span>

              <span class="h3 d-block">
                21
              </span>
            </div>
          </div>
        </div>

        <div class="col-6 mb-2 bg-orange px-0">
          <div class="img-meal">
            <% if @offer.photo.attached? %> 
              <%= cl_image_tag(@offer.photo.key, height: 270, width: "100%") %>
            <% end  %>
          </div>
          <div class="box-meal-content">
            <div>
              <div class="title-meal d-block mt-3 font-weight-bold pl-4">
                <%= @offer.title %>
              </div>
              <div class="desc-meal pl-4 py-2">
                        <%# Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. %>
                <%= @offer.description %>
              </div>
              <div class="adress-meal pl-4 py-2 mb-5">
              <i class="fas fa-map-marker-alt mr-2"></i> <%= @offer.address %>
              </div>
            </div>
            <div>
              <%# <div class="date-meal bg-orange-second col-3 my-1 d-inline-block text-center">
                <%= @offer.date %>
              <%# </div> %>
              <%= link_to "Reserver pour le #{@offer.date}", offer_reservations_path(@offer), class: "btn-resa p-3 d-block text-center mx-4 reservation-show-button text-decoration-none", method: :post %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/offers/test.ined.html.erb
<div class="search-container"> 
  <div>
    <h1 class="title">Nous avons trouvé<span class="color"> <%= Offer.count %> offres</span></h1>
  </div>
  <div class= "search-form">
    <%= form_tag offers_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Recherchez un hobby"
      %>
      <%= submit_tag "Rechercher", class: "btn search" %>
    <% end %>
  </div>
</div>
<div class="main-container">
  <% @offers.each do |offer| %>
    <div class="wrapper">
      <%= link_to offer_path(offer) do %> 
        <%= cl_image_tag(offer.photo.key.to_s, class:"plat", width: 150, height: 150, crop: :thumb, gravity: :face) %>
        <h1><%= offer.title %> </h1> 
        <p class="description"><%= offer.description %> </p>
        <% offer.tag_list.first&.split(" ")&.each do |tag| %>
          <div class="tags"> 
            <%= tag %>
        <% end %>
 
          <% if offer.user.avatar.attached? %>
        <%= cl_image_tag(offer.user.avatar.key, lass:"plat", width: 150, height: 150, crop: :thumb, gravity: :face) %>
      <% else %>
          <%=  cl_image_tag ("user.png") %>
      <% end %>
    <% end %>
    </div>
  <% end  %>
    <div id="map" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>" data-markers="<%= @markers.to_json %>"></div>
</div>