config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :offers do
    resources :reservations, only: [:new, :create]
  end
  post '/reservations/:id/deny', to: 'reservations#deny', as: 'reservation_deny'
  post '/reservations/:id/accepted', to: 'reservations#validate', as: 'reservation_validate'

  resources :reservations, only: [:index]
  #, only: [:destroy, :index]
  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :offer
  enum status: {
    "pending" => 0,
    "accepted" => 1,
    "denied" => 2
  }

  def start_time
    offer.date
  end

  def status
    if super == 'accepted' && offer.date < Date.today
      'completed'
    else
      super
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_offer, only: [:new, :create]
  skip_after_action :verify_authorized

  def index
    # @reservations = Reservation.all
    start_date = params.fetch(:date, Date.today).to_date
    
    # Offre créée par le User senior
    @my_offers = Offer.where(user: current_user)

    @my_pending_offers = @my_offers.joins(:reservation).where(reservation: {status: "pending"})

    @reservations =
      policy_scope(Reservation)
        .joins(:offer)
        .where(user_id: current_user.id)
        .or(Reservation.joins(:offer).where(offer: { user_id: current_user.id }))
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new
    @reservation.offer = @offer
    @reservation.user = current_user
    user_senior = @reservation.offer.user
    user_junior = @reservation.user
    if @reservation.save
      if current_user.role == "junior"
        @chatroom = Chatroom.find_or_create_by(
          name: "#{user_senior.full_name}",
          user_senior: user_senior,
          user_junior: user_junior
        )
      else
        @chatroom = Chatroom.find_or_create_by(
          name: "#{user_junior.full_name}",
          user_senior: user_senior,
          user_junior: user_junior
        )
      end
      redirect_to reservations_path, notice: "La réservation a été enregistrée avec succès !"
      # @reservation.status = "En attente de validation"
      # redirect_to reservations_path
    else
      render "reservations/show"
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    authorize @reservation
    @reservation.destroy
    redirect_to reservations_path, notice: "La réservation a été supprimée avec succès !"
  end

  def edit
  end

  # def update
  #   @reservation = Reservation.find(params[:id])
  #   @reservation.status = params[:reservation][:status]
  #   @reservation.save
  #   authorize @reservation
  #   user_senior = @reservation.offer.user
  #   user_junior = @reservation.user
  #   if @reservation.accepted?
  #     @chatroom = Chatroom.find_or_create_by(
  #       name: "#{user_senior.full_name} & #{user_junior.full_name}",
  #       user_senior: user_senior,
  #       user_junior: user_junior
  #     )
  #     redirect_to chatroom_path(@chatroom) and return
  #   end
  #   # TODO : redirect to a proper view
  #   redirect_to root_path
  # end

  def validate
    @reservation = Reservation.find(params[:id])
    authorize @reservation
    @reservation.status = "accepted"
    @reservation.save
    redirect_to reservations_path
  end

  def deny
    @reservation = Reservation.find(params[:id])
    authorize @reservation
    @reservation.status = "denied"
    @reservation.save
    redirect_to reservations_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:user_id, :offer_id)
  end

  def set_offer
    @offer = Offer.find(params[:offer_id])
    authorize @offer
  end
end

app/views/reservations/partials/_calendar.html.erb
<div id="calendar" class="calendar all">
  <div>
    <% @my_pending_offers.each do |offer| %>
      <%= link_to(offer_path(offer), class: 'text-decoration-none') do %>
        <div class="card-product my-3">
          <%= cl_image_tag(offer.photo.key) %>

          <div class="card-product-infos">
            <h2 class="text-dark"><%= offer.title %></h2>
            <p class="text-dark"><%= l(offer.date, format: :long) %></p>
            <div>  
              <%= link_to "Valider", reservation_validate_path(offer.reservation), class:"btn btn-ghost", method: :post%> 
              <%= link_to "Refuser", reservation_deny_path(offer.reservation), class:"btn btn-ghost", method: :post%> 
            </div>
          </div>
        </div>
      <% end %>
    <% end %> 
  </div>
  <%= month_calendar events: @reservations do |date, reservations| %>
    <%= date %>
    <% reservations.each do |reservation| %>
      <div class="reservation <%= reservation.status %>">
        <p><%= link_to "#{reservation.offer.title}", offer_path(reservation.offer.id), class:"color-font-reservation"%></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/reservations/partials/_header.html.erb
<div id="dashboard-header" class="d-flex align-items-center justify-content-start">
  <div class="mr-2">
    <button id="all" class="btn px-3 py-2 active">
      Mes demandes
    </button>
  </div>
  <div class="mr-2">
    <button id="accepted" class="btn px-3 py-2">
      Déjeuners à venir
    </button>
  </div>
  <div class="mr-2">
    <button id="completed" class="btn px-3 py-2">
      Déjeuners passés
    </button>
  </div>
  <% if current_user.role == 'senior' %>
    <div class="mr-2">
      <button id="senior-reservations" class="btn px-3 py-2">
        Mes invitations en ligne
      </button>
    </div>
  <% end %>
</div>